#!/bin/bash
set -e

/etc/shibboleth-ds/build-federation.sh
/etc/shibboleth/shibd-redhat start

# Apache gets grumpy about PID files pre-existing
rm -f /run/httpd/httpd.pid
# Also from pre-existing digest auth files
rm -f /run/httpd/authdigest_shm.*
exec httpd -DFOREGROUND
